# This workflow will build the app.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: App Build

env:
  POSTGRES_HOST: localhost
  POSTGRES_DB: userhours_dev
  POSTGRES_USER: userhours_user
  POSTGRES_PASSWORD: Super-e3cret

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  app-test:

    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up the DB
        run: |
          make build-db
